using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NetSimulation.Lib;
using NetSimulation;
using Mathutil;
using System.Diagnostics;
using BasicNet;
using BasicNet.Examination;
using System.Threading;
using System.Threading.Tasks;
using System.IO;
using System.Collections.Concurrent;
namespace NetworkRobustness.Lib
{
     
    public class CommandFunction
    {
        public static TextCommand[] appCommands = new TextCommand[] 
        {
            new TextCommand(false, "checknetwork","Check the validity of a network file", OnCheckNetwork,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network data file name",""), 
             
                }),
                 new TextCommand(false, "rewire","Rewire (shuffle) arcs of a directed network while preseving node degree (data for Fig.2)", OnNetworkRewireCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network data file name","STKEnn3.txt"), 
                    new KeyValuePair<string,object>("The number of rewired networks",20),
                    new KeyValuePair<string,object>("The range of perturbation From [0-1]",0.1),  
                    new KeyValuePair<string,object>("The range of perturbation To [0-1]",1),
                    new KeyValuePair<string,object>("Calculate modularity while rewiring the network? (true/false)",false),
                    new KeyValuePair<string,object>("Calculate robustness while rewiring the network? (true/false)",false)
                }),
                new TextCommand(false, "moro.ba","The relationship between modularity and robustness on RBNs generated by BA network model (data for Fig.3 & Fig.4)", OnAnalyzeModularityRobustnessRelationship,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("# of networks",5000), 
                    new KeyValuePair<string,object>("The range of node From",50),
                    new KeyValuePair<string,object>("The range of node To",50),  
                    new KeyValuePair<string,object>("The range of link From",49),
                    new KeyValuePair<string,object>("The range of link To",245),
                    new KeyValuePair<string,object>("Report file name","moro.ba.rel.txt")
                }),
                 new TextCommand(false, "multimutation.ba","The relationship between modularity and robustness with mutiple mutations on RBNs", OnMoRoMutipleMutations,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("# of networks",5000), 
                    new KeyValuePair<string,object>("The range of node From",30),
                    new KeyValuePair<string,object>("The range of node To",30),  
                    new KeyValuePair<string,object>("The range of link From",29),
                    new KeyValuePair<string,object>("The range of link To",100),
                    new KeyValuePair<string,object>("Report file name","multimutation.ba.rel.txt")
                }),
                new TextCommand(false, "morohc.ba","The relationship between modularity, robustness, and HC entropy in BA network model", OnAnalyzeMoRoHC,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("# of networks",5000), 
                    new KeyValuePair<string,object>("The range of node From",50),
                    new KeyValuePair<string,object>("The range of node To",50),  
                    new KeyValuePair<string,object>("The range of link From",49),
                    new KeyValuePair<string,object>("The range of link To",245),
                    new KeyValuePair<string,object>("Report file name","hcentropy.ba.rel.txt")
                }),

                 new TextCommand(false, "moro.density","The relationship between modularity and robustness on RBNs generated by BA model with a given range of network density (data for Fig. 3 & Fig.4)", OnFastDensityCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The range of density From",0.03),
                    new KeyValuePair<string,object>("The range of density To",0.03),
                    new KeyValuePair<string,object>("The range of node From",50),
                    new KeyValuePair<string,object>("The range of node To",200),  
                    new KeyValuePair<string,object>("# of networks",5000)
                }),
                  new TextCommand(false, "disease.net","Create disease network (data for Fig. 5)", OnCreateDiseaseMap,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The file with three columns (Gene, ModuleID, DiseaseID)","disease.graph.txt")
                 
                }),
                new TextCommand(false, "matrixtolist.net","Convert a matrix network file to a edge list network", OnConvertMatrixToEdge,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The file name","matrix.net.txt")
                 
                }),
                new TextCommand(false, "moro.bench","The relationship between modularity and robustness on benchmark networks, see Physical Review E80, 016118 (2009) (for comments of Referee 2)", OnMoRoBenchmarkCommand2,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("# of benchmark networks",1000), 
                    new KeyValuePair<string,object>("# of node in each network From",50),
                    new KeyValuePair<string,object>("# of node in each network To",200),
                    new KeyValuePair<string,object>("Average of in-degree (0 = random)",2.1538),//HSN2013=6.9195
                    new KeyValuePair<string,object>("Maximum in-degree (0 = random)",31),//HSN2013=248
                    new KeyValuePair<string,object>("Minus exponent for degree distribution (0 = random) ",0.0),//STKE=1.998 HSN2013=1.529
                    new KeyValuePair<string,object>("Modularity type (1 = directed weighted, 2 = undirected weighted, otherwise = undirected unweighted)",1),
                    new KeyValuePair<string,object>("Output report file name","moro.bench.txt")
                }),
                 new TextCommand(false, "comp.bench","Compare performance of 3 modularity functions on benchmark networks, Physical Review E80, 016118 (2009) (to prove that network directionality is not an obstacle to modularity analysis)", OnCompareBenchmarkCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("# of benchmark networks",1000), 
                    new KeyValuePair<string,object>("# of node in each network From",20),
                    new KeyValuePair<string,object>("# of node in each network To",50),
                    new KeyValuePair<string,object>("Minus exponent for degree distribution (0 = random) ",2),
                    new KeyValuePair<string,object>("Output report file name","compare.bench.txt")
                }),
                 new TextCommand(false, "comp.modularity","Compare performance of 3 modularity functions on RBNs (to prove that network directionality is not an obstacle to modularity analysis)", OnCompareModularityFunction,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("# of networks",5000), 
                    new KeyValuePair<string,object>("The range of node From",50),
                    new KeyValuePair<string,object>("The range of node To",50),  
                    new KeyValuePair<string,object>("The range of link From",49),
                    new KeyValuePair<string,object>("The range of link To",245),
                    new KeyValuePair<string,object>("Report file name","comp.modularity.txt")
                }),

                 new TextCommand(false, "robustnesspvalue","P-value of robustness for the approximate calculation", OnCalculateRobustnessPvalue,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("# of networks",100), 
                    new KeyValuePair<string,object>("Sample size of network states on each network",30),
                    new KeyValuePair<string,object>("The range of node From",20),
                    new KeyValuePair<string,object>("The range of node To",40),  
                    new KeyValuePair<string,object>("Report file name","report.txt"),
                    new KeyValuePair<string,object>("Does it create the most sparse networks (y/n)?","y")
                }),
                 new TextCommand(false, "gen.bench","Generate a sample of a directed, weighted, and overlapping benchmark graph for community detection algorithms, Physical Review E80, 016118 (2009)", OnBenchmarkCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("# of nodes in the creating network",50),
                    new KeyValuePair<string,object>("Average of in-degree (<k>)",2.1538),
                    new KeyValuePair<string,object>("Maximum in-degree",31),
                    new KeyValuePair<string,object>("Minus exponent for degree distribution (γ)",2),
                    new KeyValuePair<string,object>("Minus exponent for community-size distribution (β)",1),
                    new KeyValuePair<string,object>("The fraction of links connecting with other diffent-community nodes (mixing parameter, μ)",0.5),
                    new KeyValuePair<string,object>("# of overlapping nodes",0),  
                    new KeyValuePair<string,object>("# of overlap membership",0),
                    new KeyValuePair<string,object>("Minimum for the community sizes",10),
                    new KeyValuePair<string,object>("Maximum for the community sizes",20),
                    new KeyValuePair<string,object>("Fixing range",false),
                    new KeyValuePair<string,object>("Allowing excess",false),
                    new KeyValuePair<string,object>("Allowing defect",false),
                    new KeyValuePair<string,object>("Output network file","Benchmark.txt")
                }),
                
                new TextCommand(false,"gen.ba","Create a sample of random scale-free network by Barabasi model", CreateScaleFreeNetworkBA,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The number of nodes",50),
                    new KeyValuePair<string,object>("The number of links",100),
                    new KeyValuePair<string,object>("Network result file","ba.net.txt")
                }),
                
                new TextCommand(false, "cal.net","Calculate modularity, robustness, controllability, and density of a network or folder", OnNetworkParameterCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network data file name","STKEnn3.txt")
                }),
                 new TextCommand(false,"module","Detect modules of a network", OnComputingModularityFileCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The network file name","STKEnn3.txt"),
                    new KeyValuePair<string,object>("Modularity function (1 = directed weighted, 2 = undirected weighted, otherwise = undirected unweighted)",2),
                    new KeyValuePair<string,object>("Result file name","mo.file.txt")
                }),
                 
                new TextCommand(false, "rewire.analysis","Analysis Mo & Ro with rewired networks while preseving node degree", OnNetworkRewireNetworkAnalysisCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network data file name","net.txt"), 
                    new KeyValuePair<string,object>("The range of perturbation From [0-1]",0.1),  
                    new KeyValuePair<string,object>("The range of perturbation To [0-1]",1),
                    new KeyValuePair<string,object>("The number of rewired networks",20)
                }),
                // new TextCommand(false,"gen.conf","Create random scale-free multiple-graph network by configure model", CreateScaleFreeNetworkConfigure,new KeyValuePair<string,object>[]
                //{
                //    new KeyValuePair<string,object>("The number of nodes",50),
                //    new KeyValuePair<string,object>("Exponent for In-degree distribution",2.0),
                //    new KeyValuePair<string,object>("Exponent for Out-degree distribution",2.0),
                //    new KeyValuePair<string,object>("Network result file","conf.net.txt")
                //}),
                // new TextCommand(false, "moro.conf.rel","The relationship between modularity and robustness with configure network model", OnAnalyzeMoRoByConfigureModel,new KeyValuePair<string,object>[]
                //{
                //    new KeyValuePair<string,object>("# of networks",10), 
                //    new KeyValuePair<string,object>("The range of node From",20),
                //    new KeyValuePair<string,object>("The range of node To",40),  
                //    new KeyValuePair<string,object>("Powerlow of In-degree (0 = random; >2 sparse network)",0.0),
                //    new KeyValuePair<string,object>("Powerlow of Out-degree (0 = random; >2 sparse network)",0.0),
                //    new KeyValuePair<string,object>("Report file name","report.txt")
                //}),
                //<--------- End the first paper
                //---------> Begin the second paper
            //    new TextCommand(false, "densitycentrality","Analyzing centrality on RBNs with density fixed", OnDensityCentralityCommand,new KeyValuePair<string,object>[]
            //    {
            //        new KeyValuePair<string,object>("The range of density From",0.03),
            //        new KeyValuePair<string,object>("The range of density To",0.03),
            //        new KeyValuePair<string,object>("The range of node From",20),
            //        new KeyValuePair<string,object>("The range of node To",40),  
            //        new KeyValuePair<string,object>("# of networks",10)
            //    }),
            //new TextCommand(false, "mo.layer","Analyze different modularity of modular layers of a network", OnModularityCommand,new KeyValuePair<string,object>[]
            //    {new KeyValuePair<string,object>("Network data file name","hsn.txt")}), 

            new TextCommand(false,"mo.folder","Computing network modularity from all files in a folder", OnComputingModularityFolderCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The folder contains network files to compute modularity",""),
                    new KeyValuePair<string,object>("Modularity type (1 = directed weighted, 2 = undirected weighted, otherwise = undirected unweighted)",1),
                    new KeyValuePair<string,object>("Result file name","mo.folder.txt")
                }),
                
            new TextCommand(false,"avghc.folder","Computing network average HC from all files in a folder", OnComputingAverageHCFolderCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The folder contains network files to compute modularity",""),
                    new KeyValuePair<string,object>("Result file name","avghc.folder.txt")
                }),
                
            new TextCommand(false,"hcentropy.folder","Computing network HC entropy from all files in a folder", OnComputingHcEntropyFolderCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The folder contains network files to compute modularity","ParsedByKEGGgraph_New2"),
                    new KeyValuePair<string,object>("Result file name","hcEntropy.folder.txt")
                }),
            new TextCommand(false,"hcentropy.corenet.folder","Computing core-network HC entropy from all files in a folder", OnComputingHcEntropyWithTheNetCoreFolderCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The folder contains network files to compute modularity","ParsedByKEGGgraph_New2"),
                    new KeyValuePair<string,object>("R-CORE method(0) or K-CORE method(1) = {0,1}",0),
                    new KeyValuePair<string,object>("1: core without peripheral, 2: second-innermost core, 3: innermost core ={1,2,3}",1),
                    new KeyValuePair<string,object>("Result file name","hcEntropy.corenet.folder.txt")
                }),
             new TextCommand(false,"parse Kegg xml","Parse Kegg Xml files in a folder in to network format file", OnParseKeggXMLFolderCommand,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The folder contains kegg xml files to parse","DrilledByCyKEGGParser2"),
                    new KeyValuePair<string,object>("Result output folder name","ParseDrilled2"),
                    new KeyValuePair<string,object>("Parsing option: 0) decomposing at group level, 1) decomposing at gene level  (0/1)",0)
                }),
                
            new TextCommand(false,"remove links","Removing links by their type from all networks in a folder", OnRemoveNetworkLink,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("The input folder contains network files to remove links",""),
                    new KeyValuePair<string,object>("Type of links to be removed",0),
                    new KeyValuePair<string,object>("The output folder contains network files with removed links","LinkRemoval")
                }),
            new TextCommand(false,"degree","Calculating in-degree and out-degree distribution of all networks in a folder", OnAnalyzeNetworkDegreeDistribution,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file","hsn.txt")

                }),
                
            new TextCommand(false, "thesamesizegroup","Randomly select the size groups of objects", OnSelectRandomObjectByGroup,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Data file name composed of two columns (ObjectID, GroupID) whose header is not included in the file","Group.txt"), 
                    new KeyValuePair<string,object>("The result file in the form of (ObjectID, GroupID) where groups have the same size","GroupResult.txt"),
                    new KeyValuePair<string,object>("The desired size of groups",100),  
                }),
 
            //new TextCommand(false,"comp.modulegroup","Comparision of Mo & Ro between Modules and Group", OnMoRoOnModuleAndRandomGroup,new KeyValuePair<string,object>[]
            //    {
            //        new KeyValuePair<string,object>("# of networks",10), 
            //        new KeyValuePair<string,object>("The range of node From",20),
            //        new KeyValuePair<string,object>("The range of node To",40),  
            //        new KeyValuePair<string,object>("The range of link From",19),
            //        new KeyValuePair<string,object>("The range of link To",100),
            //        new KeyValuePair<string,object>("Report file name","report.txt")
            //    }),
#if PROCESS_NET
                new TextCommand(false,"Process@Net","Analyze networked workflows in a file or a folder", OnComputeCentrality,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file/folder","net.txt")
                    
                }),
#else
            new TextCommand(false,"node.analysis","Compute Centrality and ModuleID of nodes in the networks in a file or a folder", OnComputeCentrality,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file/folder","net.txt")
                }),
#endif
             new TextCommand(false,"core.decomposition","Decompose K-/R- core of a file or a folder", OnCoreDecomposition,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file/folder","net.txt")
                    
                }),



            new TextCommand(false,"cen.rbn","Analyze centrality layers on the random network", OnAnalyzeCentralityLayer,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("# of networks",1000), 
                    new KeyValuePair<string,object>("The range of node From",50),
                    new KeyValuePair<string,object>("The range of node To",50),  
                    new KeyValuePair<string,object>("The range of link From",49),
                    new KeyValuePair<string,object>("The range of link To",245),
                    new KeyValuePair<string,object>("Report file name","centrality.rbn.txt")
                }),
                 new TextCommand(false,"competitors","Find supporters of the competitors in a network", OnCalculateCompetitiveNetwork,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Competitive network file name","a.txt"), 
                    new KeyValuePair<string,object>("The Positive competitors (separated by signs: comma, semicolon)","1, 2"), 
                    new KeyValuePair<string,object>("The Negative competitors (separated by signs: comma, semicolon)","10; 3"), 
                    new KeyValuePair<string,object>("Report file name","competition.txt")
                }),
                  new TextCommand(false,"competitiveranking","Analyze competitive centrality of a network", OnCalculateCompetitiveRanking,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Competitive network file name","a.txt"), 
                    
                    new KeyValuePair<string,object>("Report file name","competitiveRanking.txt")
                }),
                new TextCommand(false,"loyalmatrix","Calculate the loyal points of supporters to a given node against the strong opposite signal from outside", OnCalculateLoyalMatrixPoint,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Competitive network file name","C4rd.txt"), 
                    
                    new KeyValuePair<string,object>("Report file name","Loyalness.txt")
                }),
                
                new TextCommand(false,"loyal","Calculate the loyal points of supporters to a given node against the strong opposite signal from outside", OnCalculateLoyalPointWithLeader,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Competitive network file name","C4rd.txt"), 
                    new KeyValuePair<string,object>("Leader's name",""),
                    new KeyValuePair<string,object>("Report file name","leader.txt")
                }),
                 new TextCommand(false,"Total support","Calculate total support of all node against the strong opposite signal from outside", OnCalculateTotalSupport,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file name","C4rd.txt"),
                    new KeyValuePair<string,object>("Total support result","Totalsupport.txt")
                }),

                new TextCommand(false, "DiSC network simulation", "Generate multiple scale-free directed networks using DiSC attachment strategies (D,I,S,C)", OnDiSCNetworkSimulation, new KeyValuePair<string, object>[]
                {
                    new KeyValuePair<string,object>("# of networks",1000),
                    new KeyValuePair<string,object>("The range of node From",100),
                    new KeyValuePair<string,object>("The range of node To",200),
                    new KeyValuePair<string,object>("The range of link From",2),
                    new KeyValuePair<string,object>("The range of link To",6),
                    new KeyValuePair<string,object>("Report file name","disc.ba.rel.txt")
                }),

                new TextCommand(false,"optimum.branching","Finding Optimum branchings", OnCalculateOptimumBranchings,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file name","net.txt"),
                    new KeyValuePair<string,object>("Report file name","report.txt")
                }),
                
            //    new TextCommand(false,"fixedreachingcentrality","Analyze centrality layer on the random network with fixed reaching", OnAnalyzeCentralityLayerWithFixedReaching,new KeyValuePair<string,object>[]
            //    {
            //        new KeyValuePair<string,object>("Report file name","report.txt")
            //    }),

                 

            //    new TextCommand(false, "modularitydistribution","Modularity distribution", OnModularityDistributionCommand,new KeyValuePair<string,object>[]
            //    {
            //        new KeyValuePair<string,object>("The signaling network file","HSN.txt"), 
            //        new KeyValuePair<string,object>("The number of simulated networks",20),
            //        new KeyValuePair<string,object>("Report file name","report.txt")
            //    }),

            //    new TextCommand(false, "analyzemmodulerobustness","Analyze module robustness", OnAnalyzeModuleRobustness,new KeyValuePair<string,object>[]
            //    {
            //        new KeyValuePair<string,object>("# of networks",10), 
            //        new KeyValuePair<string,object>("The range of node From",20),
            //        new KeyValuePair<string,object>("The range of node To",40),  
            //        new KeyValuePair<string,object>("The range of link From",19),
            //        new KeyValuePair<string,object>("The range of link To",100),
            //        new KeyValuePair<string,object>("Report file name","report.txt")
            //    }),

            

                 //<----- End second paper
                
                new TextCommand(false,"network.foci","Determine the number of foci (number of triadic closure) of a social network (undirected network)", 
                    OnFociNetwork,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file name","karate.txt")
                }),

                new TextCommand(false,"network.graphFoci","Convert foci graph to social network (undirected network)", 
                    OnGraphFociNetwork,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file name","karate.txt")
                }),

                new TextCommand(false,"network.balance","Balance the network with two positive"+
                 "and negative relations in balance network: weight = -1 -> negative relationship"+
                 " and weight = 1 -> positive relationship",
                 OnBalanceCommucation,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file/folder","net.txt"),
                }),

                new TextCommand(false,"network.convert","Convert social network to balance network:"+
                  "negative relationship -> weight = -1 and positive relationship -> weight = 1 ",
                 OnConvertCommucation,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file/folder","net.txt"),
                }),
                 new TextCommand(false,"Scc.InNetwork","Decomposition a directed network into 6 parts: 1.giant strong connected component (SCC), 2.Input, 3.Output, 4.Tube, 5.Tendrils, and 6.Disconnected", FindSccInOut,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file/folder","net.txt")
                }),
                 new TextCommand(false,"gateKeeper.check","Identify the gatekeepers in the directed-/undirected- network", GateKeeperCheck,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file/folder","net.txt")
                }),
                  new TextCommand(false,"find driver nodes","Identify driver nodes from an directed-/undirected- network", FindDriverNode,new KeyValuePair<string,object>[]
                {
                    new KeyValuePair<string,object>("Network file/folder","net.txt")
                }),

        };

        #region Command functions
        /// <summary>
        /// Tùng cài đặt thuật toán tìm driver node từ bài báo https://www.nature.com/articles/ncomms3447
        /// </summary>
        /// <param name="Parameter">1 file text nằm trong thư mục Input tối thiểu 2 cột: Start\tEnd\tWeight</param>
        private static void FindDriverNode(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            // Cài đặt thuật toán ở đây
            string networkFileName = Convert.ToString(Parameter[0].Value);

            BasicNet.Examination.SignalingStudy.FindDriverNode(networkFileName);

        }


        #region Application functions
        private static void OnModularityCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string fileName = Convert.ToString(Parameter[0].Value);
            BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileName);
            Netutil.AnalysisModuleToTextFile(net, Netutil.ExtractMainFileName(fileName)+".ModuleAnalysis." + ".txt");
            
        }

        private static void OnFociNetwork(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            String networkFile = Convert.ToString(Parameter[0].Value);
            BasicNet.Examination.SignalingStudy.FociNetwork(networkFile);

        }  
        
        private static void OnGraphFociNetwork(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            String networkFile = Convert.ToString(Parameter[0].Value);
            BasicNet.Examination.SignalingStudy.GraphFociNetwork(networkFile);

        }

        private static void OnBalanceCommucation(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string networkFileName = Convert.ToString(Parameter[0].Value);
            BasicNet.Examination.SignalingStudy.BalanceCommucation(networkFileName);
        }

        private static void OnConvertCommucation(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string networkFileName = Convert.ToString(Parameter[0].Value);
            BasicNet.Examination.SignalingStudy.ConvertCommucation(networkFileName);
        }
        private static void FindSccInOut(Dictionary<int, KeyValuePair<string, object>> Parameter)
         {
            string networkFileName = Convert.ToString(Parameter[0].Value);
            BasicNet.Examination.SignalingStudy.ComputeConnected(networkFileName);
            
            //User.One.MessageToUser(inputFolder);
         }

        public static void GateKeeperCheck(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            String networkFile = Convert.ToString(Parameter[0].Value);
            BasicNet.Examination.SignalingStudy.CheckGateKeeper(networkFile);
        }

        private static void CreateScaleFreeNetworkBA(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int Node = Convert.ToInt32(Parameter[0].Value);
            int Link = Convert.ToInt32(Parameter[1].Value);
            string FileName = Convert.ToString(Parameter[2].Value);
            FileName = Netutil.ExtractMainFileName(FileName) + "." + Node.ToString() + "." + Link.ToString() + ".txt";
            ComplexNetGenerator netGen = new ComplexNetGenerator();
            BooleanNetwork net = (BooleanNetwork)netGen.generateDirectedNetworkByPreferentialAttachment(new BooleanNetwork(), Node, Link);
            double inGamma=0, inR=0,inPValue=0,outGamma=0,outR=0,outPValue=0;
            Netutil.FitDegreeDistribution(net, ref inGamma, ref inR, ref inPValue, ref outGamma, ref outR, ref outPValue);
            string NetworkParameter = string.Format("In-Gamma = {0}\tR(P(k), in-degree rate) = {1}\t P-value ={2}\nOut-Gamma = {3}\tR(P(k), out-degree rate) = {4}\t P-value ={4}",
                inGamma, inR, inPValue, outGamma, outR, outPValue);
            
            User.One.MessageToUser(string.Format("The network is saved at {0}", Netutil.WriteGraphToTextFile(net, FileName)));
            User.One.MessageToUser("\nParameters of the network generated:\n" + NetworkParameter);
        }
        private static void CreateScaleFreeNetworkConfigure(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
             //new KeyValuePair<string,object>("The number of nodes",50),
             //       new KeyValuePair<string,object>("Exponent for In-degree distribution (0 = random) ",2),
             //       new KeyValuePair<string,object>("Exponent for Out-degree distribution (0 = random) ",2),
             //       new KeyValuePair<string,object>("Network result file","conf.net.txt")

            int Node = Convert.ToInt32(Parameter[0].Value);
            double InGamma = Convert.ToDouble(Parameter[1].Value);
            double OutGamma = Convert.ToDouble(Parameter[2].Value);
            string FileName = Convert.ToString(Parameter[3].Value);

            if (InGamma <= 1.0 || OutGamma <= 1.0)
                throw new Exception("Exponent for distribution have to >1");
            NumericMath.RandomCraft rand=new NumericMath.RandomCraft(NumericMath.RandomCraft.Next(1,int.MaxValue-1));
            ComplexNetGenerator netGen = new ComplexNetGenerator();
            BooleanNetwork net = (BooleanNetwork)netGen.GenConfModel4Directed(new BooleanNetwork(), Node, InGamma, OutGamma, rand);
            User.One.MessageToUser(string.Format("The network is saved at {0}", Netutil.WriteGraphToTextFile(net, FileName)));
        }
        private static void OnDiSCNetworkSimulation(
    Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int nNet = Convert.ToInt32(Parameter[0].Value);
            int nNodeFrom = Convert.ToInt32(Parameter[1].Value);
            int nNodeTo = Convert.ToInt32(Parameter[2].Value);
            int nMinLink = Convert.ToInt32(Parameter[3].Value);
            int nMaxLink = Convert.ToInt32(Parameter[4].Value);
            string reportFileName = Convert.ToString(Parameter[5].Value);

            BasicNet.Examination.SignalingStudy.DiSCNetworkSimulation(nNet, nNodeFrom, nNodeTo, nMinLink, nMaxLink, reportFileName);
        }
        private static void OnCreateDiseaseMap(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string DiseaseFile = Convert.ToString(Parameter[0].Value);
            BasicNetwork Net = BasicNet.Examination.CreateGraphTool.CreateDiseaseFullGraphFromFile(DiseaseFile);
            if (Net.Nodes.Count() > 0)
                User.One.MessageToUser("Succesfully create the network!\nA grap text file with format (start, end, weight, subtype (disease ID), type (ID of In module or Out module)");
            else
                User.One.MessageToUser("Unsuccesfully create the network!");
        }
        private static void OnConvertMatrixToEdge(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string MatrixNetFile = Convert.ToString(Parameter[0].Value);
            BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(MatrixNetFile);
            string OutPut= Netutil.ExtractMainFileName(MatrixNetFile)+".edge.txt";
            net.WriteToFile(OutPut);

            if (net.Nodes.Count() > 0)
                User.One.MessageToUser("an edge network file is saved at '"+OutPut+"' with "+net.Nodes.Count()+" nodes and "+net.Arcs.Count()+" arcs");
            else
                User.One.MessageToUser("Unsuccesfully load the network!");
        }
        private static void OnComputingModularityFileCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string fileName = Netutil.GetFullInputFileName(Convert.ToString(Parameter[0].Value).Trim());
            int MoType = Convert.ToInt32(Parameter[1].Value);
            string resultFile = Convert.ToString(Parameter[2].Value).Trim();

            string moTypeName = MoType == 1 ? "directed weighted" : (MoType == 2 ? "undirected weighted" : "undirected unweighted");
            User.One.MessageToUser(string.Format("The modularity is for a '{0}' network", moTypeName));
            
            
            BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileName);

            User.One.MessageToUser("Calculating...");
            Dictionary<Node, int> pCluster = null;
            //double mo = (MoType == 1 ? net.modularityWeightedDirected(ref pCluster) :
            //    (MoType == 2 ? net.modularity(ref pCluster, true) :
            //    net.modularity(ref pCluster, false)));
            double mo =-1;
            if (MoType == 1)
                pCluster = BasicNet.OptimizerModularityDirected.ClusterGraphExactly(net, ref mo);
            else if (MoType == 2)
                pCluster = BasicNet.OptimizerModularityExactly.ClusterGraph(net, true, ref mo);
            else
                pCluster = BasicNet.OptimizerModularityExactly.ClusterGraph(net, false, ref mo);

            Netutil.WriteClusterToTextFile(mo, pCluster, resultFile);
            User.One.MessageToUser(string.Format("Modularity of {0} = {1}\nSee details in \"{2}\"", fileName, mo, resultFile));
            
        }
        private static void OnComputingModularityFolderCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string Folder = Convert.ToString(Parameter[0].Value).Trim();
            int MoType = Convert.ToInt32(Parameter[1].Value);
            string resultFile = Convert.ToString(Parameter[2].Value).Trim();

            string moTypeName=MoType == 1 ? "Directed weighted" : (MoType == 2 ? "Undirected weighted" : "Undirected unweighted");
            User.One.MessageToUser(string.Format("The modularity is for '{0}' networks", moTypeName));
            IEnumerable<string> files = Directory.EnumerateFiles(Netutil.InPutDirector + (Folder != "" ? "\\" + Folder : ""));
            int i = 1;
            TextDB.WriteTextFile(string.Format("File\t {0} modularity",moTypeName), resultFile);
            string clusterName = "";
            foreach (string fileName in files)
            {
                BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileName);
                clusterName = Netutil.ExtractMainFileName(resultFile)+"."+Netutil.ExtractMainFileName(Netutil.ExtractFileNameFromPath(fileName))+".cls.txt";
                User.One.MessageToUser(string.Format("Start \"{0}\"", fileName));
                Dictionary<Node, int> pCluster = null;

                // Computing modularity roughly by not shuffling edges
                //double mo = (MoType ==1?net.modularityWeightedDirected(ref pCluster):
                //    (MoType==2?net.modularity(ref pCluster,true):
                //    net.modularity(ref pCluster,false)));


                /// Computing modularity exactily by 10 shuffling times of edges
                double mo = -1;
                if (MoType == 1)
                    pCluster = BasicNet.OptimizerModularityDirected.ClusterGraphExactly(net, ref mo);
                else if (MoType == 2)
                    pCluster = BasicNet.OptimizerModularityExactly.ClusterGraph(net, true, ref mo);
                else
                    pCluster = BasicNet.OptimizerModularityExactly.ClusterGraph(net, false, ref mo);
                ///

                TextDB.WriteTextFile(string.Format("{0}\t{1}", Netutil.ExtractFileNameFromPath(fileName), mo), resultFile);
                Netutil.WriteClusterToTextFile(mo, pCluster, clusterName);
                User.One.MessageToUser(string.Format("Modularity is saved in \"{0}\"", clusterName));
                User.One.ShowWaitIndicator(i++, files.Count());
            }
        }
        private static void OnParseKeggXMLFolderCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string inputFolder = Convert.ToString(Parameter[0].Value).Trim();
            string outputFolder = Convert.ToString(Parameter[1].Value).Trim();
            int parsingOpt = Convert.ToInt32(Parameter[2].Value);
            Netutil.CreateOutputFolder(outputFolder);
            IEnumerable<string> files = Directory.EnumerateFiles(Netutil.InPutDirector + (inputFolder != "" ? "\\" + inputFolder : ""),"*.xml");

            int i = 1;
            foreach (string fileName in files)
            {
                BasicNetwork net = new BasicNetwork();
                BasicNetwork.ReadNetworkFromKeggXML(net, fileName, parsingOpt);
                
                net.WriteToFile(outputFolder+"\\"+Netutil.ExtractFileNameFromPath(fileName) + ".txt");
                User.One.ShowWaitIndicator(i++, files.Count());
            }

        }
        private static void OnComputingHcEntropyWithTheNetCoreFolderCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string Folder = Convert.ToString(Parameter[0].Value).Trim();
            int coreMethod = Convert.ToInt32(Parameter[1].Value);
            int kCore = Convert.ToInt32(Parameter[2].Value);
            string resultFile = Convert.ToString(Parameter[3].Value).Trim();



            IEnumerable<string> files = Directory.EnumerateFiles(Netutil.InPutDirector + (Folder != "" ? "\\" + Folder : ""));
            int i = 1;

            TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}\t{9}\t{10}\t{11}", "File ", "Node","Link", "Modularity", "HC entropy", "Reachability", "Closeness", "Degree entropy", "PageRank", "Betweeness", "K-shell", "K-coreness"), resultFile);
            foreach (string fileName in files)
            {
                BooleanNetwork onet = BooleanNetwork.ReadSignalingNetworkFile(fileName);
                IEnumerable<Node> coreNode = null;
                Dictionary<Node, int> shellcentrality = null;
                switch (coreMethod)//R-CORE
                {
                    case 0://R-CORE method selected
                        switch (kCore)
                        {
                            case 1:
                                //<---R-shell with peripheral removal
                                User.One.MessageToUser("R-shell detects the core without peripheral!");
                                shellcentrality = onet.R_ShellCentrality();
                                coreNode = from p in shellcentrality where p.Value > 1 select p.Key;
                                break;
                            case 2:
                                //<---R-shell with 2-core-- Uncomment the below lines to run
                                User.One.MessageToUser("R-shell detects the second-innermost core!");
                                shellcentrality = onet.R_ShellCentrality();
                                int border0 = shellcentrality.Values.Max();
                                int border1 = (from p in shellcentrality.Values where p < border0 select p).Max();
                                coreNode = from p in shellcentrality where p.Value >= border1 select p.Key;
                                break;
                            case 3:
                                //<---R-shell with 1 1 innermost core-- Uncomment the below lines to run
                                User.One.MessageToUser("R-shell detects the innermost core!");
                                shellcentrality = onet.R_ShellCentrality();
                                coreNode = from p in shellcentrality where p.Value == shellcentrality.Values.Max() select p.Key;
                                break;
                            default:
                                User.One.SendErrorToUser(new Exception("Select not correct parameter k-core = {1,2,}!"));
                                break;
                        }
                        break;
                    case 1:// K-CORE method selected
                        switch (kCore)
                        {
                            case 1:
                                //<---K-shell with peripheral removal
                                User.One.MessageToUser("K-shell detects the core without peripheral!");
                                shellcentrality = onet.K_ShellCentrality();
                                coreNode = from p in shellcentrality where p.Value > 1 select p.Key;
                                break;
                            case 2:
                                //<--K-shell with 2-core--
                                User.One.MessageToUser("K-shell detects the second-innermost core!");
                                shellcentrality = onet.K_ShellCentrality();
                                int border0 = shellcentrality.Values.Max();
                                int border1 = (from p in shellcentrality.Values where p < border0 select p).Max();
                                coreNode = from p in shellcentrality where p.Value >= border1 select p.Key;
                                break;
                            case 3:
                                //<--K-shell with 1 innermost core--
                                User.One.MessageToUser("K-shell detects the innermost core!");
                                shellcentrality = onet.K_ShellCentrality();
                                coreNode = from p in shellcentrality where p.Value == shellcentrality.Values.Max() select p.Key;
                                break;
                            default:
                                User.One.SendErrorToUser(new Exception("Select not correct parameter k-core = {1,2,}!"));
                                break;
                        }
                        break;
                    default:
                        User.One.SendErrorToUser(new Exception("Not selecting right core method!"));
                        break;
                }

                //var coreNode = from p in kReachingcentrality where p.Value == kReachingcentrality.Values.Max() select p.Key;
                if (coreNode.Count() == 0)
                    continue;



                BooleanNetwork net = onet.CreateNewSortestConnectionSubnetwork(coreNode) as BooleanNetwork;
                //BooleanNetwork net = onet.CreateNewExtractedSubnetwork(coreNode) as BooleanNetwork;
                net.WriteToFile("core_" + Netutil.ExtractFileNameFromPath(fileName));

                User.One.MessageToUser(string.Format("Start \"{0}\"", fileName));


                //HC entropy               
                //Dictionary<string, double> trancen = net.HierarchicalClosenessCentrality();
                Dictionary<string, Triple<double>> trancen = net.HierarchicalClosenessCentralityAnalysis();
                Dictionary<string, double> hc = new Dictionary<string, double>();
                Dictionary<string, double> reachability = new Dictionary<string, double>();
                Dictionary<string, double> closeness = new Dictionary<string, double>();
                foreach (string s in trancen.Keys)
                {
                    hc[s] = trancen[s].A;
                    reachability[s] = trancen[s].B;
                    closeness[s] = trancen[s].C;
                }


                double hcEntropy = BasicNetwork.EntropyOfNodes(hc);
                double reachEntropy = BasicNetwork.EntropyOfNodes(reachability);
                double closenessEntropy = BasicNetwork.EntropyOfNodes(closeness);

                //Degree entropy
                Dictionary<Node, double> Totaldegree = new Dictionary<Node, double>();
                Dictionary<Node, float> pagerank = net.PageRankCentralityInLink();
                Dictionary<Node, float> betweeness = net.BetweenessCentrality();
                Dictionary<Node, int> kshell = net.K_ShellCentrality();
                Dictionary<Node, int> coreness = net.K_CorenessCentrality();
                foreach (Node n in net.Nodes)
                {
                    Totaldegree.Add(n, n.TotalDegree);

                }
                double degreeEntropy = BasicNetwork.EntropyOfNodes(Totaldegree);
                double pagerankEntropy = BasicNetwork.EntropyOfNodes(pagerank);
                double betweenEntropy = BasicNetwork.EntropyOfNodes(betweeness);
                double kshellEntropy = BasicNetwork.EntropyOfNodes(kshell);
                double corenessEntropy = BasicNetwork.EntropyOfNodes(coreness);


                Dictionary<Node, int> pCluster = new Dictionary<Node, int>();
                double Mo = 0;
                pCluster = BasicNet.OptimizerModularityExactly.ClusterGraph(net, true, ref Mo);


                TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}\t{9}\t{10}\t{11}", Netutil.ExtractFileNameFromPath(fileName), net.Nodes.Count(),net.Arcs.Count(), Mo, hcEntropy, reachEntropy,
                    closenessEntropy, degreeEntropy, pagerankEntropy, betweenEntropy, kshellEntropy, corenessEntropy), resultFile);



                User.One.ShowWaitIndicator(i++, files.Count());
            }
        }
        private static void OnComputingHcEntropyFolderCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string Folder = Convert.ToString(Parameter[0].Value).Trim();
            string resultFile = Convert.ToString(Parameter[1].Value).Trim();

            
            
            IEnumerable<string> files = Directory.EnumerateFiles(Netutil.InPutDirector + (Folder != "" ? "\\" + Folder : ""));
            int i = 1;

            //TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}\t{9}", "File ", "Modularity", "HC entropy", "Reachability", "Closeness", "Degree entropy", "PageRank", "Betweeness", "k-shell", "coreness"), resultFile);
            TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}\t{9}\t{10}\t{11}\t{12}", "File ", "Node", "Link", "Modularity", "HC entropy", "Reachability", "Closeness", "Degree entropy", "PageRank", "Betweeness", "K-shell", "K-coreness","R-core"), resultFile);
            foreach (string fileName in files)
            {
                BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileName);
                
                User.One.MessageToUser(string.Format("Start \"{0}\"", fileName));

                
                //HC entropy               
                //Dictionary<string, double> trancen = net.HierarchicalClosenessCentrality();
                Dictionary<string, Triple<double>> trancen = net.HierarchicalClosenessCentralityAnalysis();
                Dictionary<string, double> hc = new Dictionary<string, double>();
                Dictionary<string, double> reachability = new Dictionary<string, double>();
                Dictionary<string, double> closeness = new Dictionary<string, double>();
                foreach (string s in trancen.Keys)
                {
                    hc[s] = trancen[s].A;
                    reachability[s] = trancen[s].B;
                    closeness[s] = trancen[s].C;
                }

                double hcEntropy = BasicNetwork.EntropyOfNodes(hc);
                double reachEntropy = BasicNetwork.EntropyOfNodes(reachability);
                double closenessEntropy = BasicNetwork.EntropyOfNodes(closeness);

                //Degree entropy
                Dictionary<Node, double> Totaldegree = new Dictionary<Node, double>();
                Dictionary<Node, float> pagerank = net.PageRankCentralityInLink();
                Dictionary<Node, float> betweeness = net.BetweenessCentrality();
                Dictionary<Node, int> kshell = net.K_ShellCentrality();
                Dictionary<Node, int> coreness = net.K_CorenessCentrality();
                Dictionary<Node, int> rshell = net.R_ShellCentrality();
                foreach (Node n in net.Nodes)
                {
                    Totaldegree.Add(n, n.TotalDegree);

                }
                double degreeEntropy = BasicNetwork.EntropyOfNodes(Totaldegree);
                double pagerankEntropy = BasicNetwork.EntropyOfNodes(pagerank);
                double betweenEntropy = BasicNetwork.EntropyOfNodes(betweeness);
                double kshellEntropy = BasicNetwork.EntropyOfNodes(kshell);
                double rshellEntropy = BasicNetwork.EntropyOfNodes(rshell);
                double corenessEntropy = BasicNetwork.EntropyOfNodes(coreness);

               
                Dictionary<Node,int> pCluster=new Dictionary<Node,int>();
                double Mo = 0;
                pCluster = BasicNet.OptimizerModularityExactly.ClusterGraph(net, true, ref Mo);


                //TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}\t{9}", Netutil.ExtractFileNameFromPath(fileName), Mo, hcEntropy, reachEntropy,
                //    closenessEntropy, degreeEntropy, pagerankEntropy, betweenEntropy, kshellEntropy, corenessEntropy), resultFile);

                TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}\t{9}\t{10}\t{11}\t{12}", Netutil.ExtractFileNameFromPath(fileName), net.Nodes.Count(), net.Arcs.Count(), Mo, hcEntropy, reachEntropy,
                    closenessEntropy, degreeEntropy, pagerankEntropy, betweenEntropy, kshellEntropy, corenessEntropy,rshellEntropy), resultFile);

                
                User.One.ShowWaitIndicator(i++, files.Count());
            }
        }
        private static void OnRemoveNetworkLink(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string InputFolder = Convert.ToString(Parameter[0].Value).Trim();
            int linkType = Convert.ToInt32(Parameter[1].Value);
            string OutputFolder = Convert.ToString(Parameter[2].Value).Trim();
            



            IEnumerable<string> files = Directory.EnumerateFiles(Netutil.InPutDirector + (InputFolder != "" ? "\\" + InputFolder : ""));
            int i = 1;

            Netutil.CreateOutputFolder(OutputFolder);
            
            foreach (string fileName in files)
            {
                
                BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileName);
                string outputfile = Netutil.ExtractFileNameFromPath(fileName);
                net.RemoveArc(true, linkType, net.Arcs.ToArray());

                net.WriteToFile(OutputFolder + "\\" + outputfile);
                //Save the network to file... next time


                User.One.ShowWaitIndicator(i++, files.Count());
            }
        }
        private static void OnComputingAverageHCFolderCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string Folder = Convert.ToString(Parameter[0].Value).Trim();
            string resultFile = Convert.ToString(Parameter[1].Value).Trim();



            IEnumerable<string> files = Directory.EnumerateFiles(Netutil.InPutDirector + (Folder != "" ? "\\" + Folder : ""));
            int i = 1;
            Dictionary<double, int> allReachabilityDistribution = new Dictionary<double, int>();
            Dictionary<double, double> allClosenessDistribution = new Dictionary<double, double>();

            foreach (string fileName in files)
            {
                BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileName);

                User.One.MessageToUser(string.Format("Start \"{0}\"", fileName));


                Dictionary<string, Triple<double>> trancen = net.HierarchicalClosenessCentralityAnalysis();

                foreach (var n in trancen)
                {
                    if (!allReachabilityDistribution.ContainsKey(n.Value.B))
                    {
                        allReachabilityDistribution[n.Value.B] = 0;
                        allClosenessDistribution[n.Value.B] = 0;
                    }

                    allReachabilityDistribution[n.Value.B] += 1;
                    allClosenessDistribution[n.Value.B] += n.Value.C;
                    
                }
                
                //double avgHC = (from p in trancen select p.Value.A).Average() / trancen.Keys.Count;
                //double avgReachablity = (from p in trancen select p.Value.B).Average() / trancen.Keys.Count;
                //double avgClosness = (from p in trancen select p.Value.C).Average();

                //Dictionary<string, double> reachabilitySeq = new Dictionary<string, double>();
                //foreach (var n in trancen)
                //{
                //    reachabilitySeq.Add(n.Key, n.Value.B);

                //}
                //double reachabilityEntropy = BasicNetwork.EntropyOfNodes(reachabilitySeq);
                //double nReachability = (from p in reachabilitySeq group p by p.Value into g select g.Key).Count();
                //double MaxReachability = (from p in reachabilitySeq select p.Value).Max();
                //double MinReachability = (from p in reachabilitySeq select p.Value).Min();

                //TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}", Netutil.ExtractFileNameFromPath(fileName), avgHC, avgReachablity, avgClosness, reachabilityEntropy, 
                //    nReachability, MaxReachability, MinReachability), resultFile);

                User.One.ShowWaitIndicator(i++, files.Count());
            }
            foreach (var n in allReachabilityDistribution)
            {
                TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}", n.Key, n.Value, allClosenessDistribution[n.Key]), resultFile);
            }
        }
        private static void OnMoRoOnModuleAndRandomGroup(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int nNet = Convert.ToInt32(Parameter[0].Value),
                  nNodeFrom = Convert.ToInt32(Parameter[1].Value),
                  nNodeTo = Convert.ToInt32(Parameter[2].Value),
                  nMinLink = Convert.ToInt32(Parameter[3].Value),
                  nMaxLink = Convert.ToInt32(Parameter[4].Value);
            string ReportFileName = Convert.ToString(Parameter[5].Value);

            BasicNet.Examination.SignalingStudy.RBN_MoRoOnModuleAndRandomGroup(nNet, nNodeFrom, nNodeTo, nMinLink, nMaxLink, ReportFileName);
        }
        

        private static void OnComputeCentrality(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string networkFileName = Convert.ToString(Parameter[0].Value);

            BasicNet.Examination.SignalingStudy.ComputeCentrality(networkFileName);
        }
        private static void OnCoreDecomposition(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string fileName = Convert.ToString(Parameter[0].Value);

            BasicNet.Examination.SignalingStudy.CoreDecomposition(fileName);
        }
        private static void OnAnalyzeCentralityLayer(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int nNet = Convert.ToInt32(Parameter[0].Value),
                  nNodeFrom = Convert.ToInt32(Parameter[1].Value),
                  nNodeTo = Convert.ToInt32(Parameter[2].Value),
                  nMinLink = Convert.ToInt32(Parameter[3].Value),
                  nMaxLink = Convert.ToInt32(Parameter[4].Value);
            string ReportFileName = Convert.ToString(Parameter[5].Value);


            BasicNet.Examination.SignalingStudy.RBN_AnalyzeCentralLayers(nNet, nNodeFrom, nNodeTo, nMinLink, nMaxLink, ReportFileName);

        }

        private static void OnAnalyzeCentralityLayerWithFixedReaching(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            //int nNet = Convert.ToInt32(Parameter[0]),
            //      nNodeFrom = Convert.ToInt32(Parameter[1]),
            //      nNodeTo = Convert.ToInt32(Parameter[2]),
            //      nMinLink = Convert.ToInt32(Parameter[3]),
            //      nMaxLink = Convert.ToInt32(Parameter[4]);
            string ReportFileName = Convert.ToString(Parameter[0].Value);


            BasicNet.Examination.SignalingStudy.RBN_AnalyzeCentralLayersWithFixedReaching(99999999, 50, 50, 49, 450, new int[] { 5 }, ReportFileName);

        }

        private static void OnDensityCentralityCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            decimal Startdensity = Convert.ToDecimal(Parameter[0].Value), Enddensity = Convert.ToDecimal(Parameter[1].Value);
            int from = Convert.ToInt32(Parameter[2].Value), to = Convert.ToInt32(Parameter[3].Value), NetNum = Convert.ToInt32(Parameter[4].Value);

            BasicNet.Examination.SignalingStudy.RBN_AnalyzeCentralLayersFixedDensity(Startdensity, Enddensity, from, to, NetNum);

        }

        private static void OnModularityDistributionCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string sgnNetwork = Convert.ToString(Parameter[0].Value);
            int nNet = Convert.ToInt32(Parameter[1].Value);
            string ReportFileName = Convert.ToString(Parameter[2].Value);

            BooleanNetwork sgnNet = BooleanNetwork.ReadSignalingNetworkFile(sgnNetwork);
            int nNode = sgnNet.Nodes.Count();
            int nLink = sgnNet.Edges.Count();
            Dictionary<Node, int> Cluster = null;
            User.One.MessageToUser("Counting modularity of the signaling network " + sgnNetwork + " with node =" + nNode.ToString() + " and link =" + nLink.ToString());
            double modularity = sgnNet.modularity(ref Cluster);

            TextDB.WriteTextFile(new string[] { "Modularity", nNode.ToString(), nLink.ToString(), modularity.ToString() }, ReportFileName);

            ComplexNetGenerator Netgen = new ComplexNetGenerator();
            for (int i = 1; i <= nNet; i++)
            {
                BooleanNetwork net = (BooleanNetwork)Netgen.generateScaleFreeUndirectedNetwork(nNode, nLink);


                modularity = net.modularity(ref Cluster);

                TextDB.WriteTextFile(new string[] { modularity.ToString() }, ReportFileName);
                User.One.ShowWaitIndicator(i, nNet);
            }
            User.One.MessageToUser("Finish modularity distribution counting at " + DateTime.Now.ToString());
        }

        private static void OnAnalyzeModuleRobustness(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int nNet = Convert.ToInt32(Parameter[0].Value),
                  nNodeFrom = Convert.ToInt32(Parameter[1].Value),
                  nNodeTo = Convert.ToInt32(Parameter[2].Value),
                  nMinLink = Convert.ToInt32(Parameter[3].Value),
                  nMaxLink = Convert.ToInt32(Parameter[4].Value);
            string ReportFileName = Convert.ToString(Parameter[5].Value);

            BasicNet.Examination.SignalingStudy.RBN_AnalyzeModuleRobustness(nNet, nNodeFrom, nNodeTo, nMinLink, nMaxLink, ReportFileName);
        }

        private static void OnNetworkParameterCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string fileFolderName = Convert.ToString(Parameter[0].Value);

            

            if (fileFolderName.LastIndexOf(".txt") > 0 || fileFolderName.LastIndexOf(".xls") > 0
                || fileFolderName.LastIndexOf(".xlsx") > 0 || fileFolderName.LastIndexOf(".xml") > 0)// not a folder
            {
                string exportFileDeviation = Netutil.ExtractMainFileName(fileFolderName) + ".NetworkParameter." + DateTime.Today.ToString("yyyy.mm.dd") + ".txt";

                BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileFolderName);
                
                Dictionary<Node, int> pCluster = null;

                double mo = net.modularityWeightedDirected(ref pCluster);
                string result = string.Format("Signaling network file \"{0}\" \n\tRobustness = {1}\n\tModularity ={2}\n\tDensity ={3}\n# of driver nodes={4}/{5}", fileFolderName, net.NetworkMutantRobustnessParalell(), mo, net.ArcDensity, net.driverNodes.Count(), net.Nodes.Count());
                User.One.SendCalculationResult(result);
                User.One.MessageToUser("Please see file: " + exportFileDeviation);
                //User.One.MessageToUser("\nCluster at " + Netutil.WriteClusterToTextFile(Cluster, "Modules." + net.Name + ".txt"));
                TextDB.WriteTextFile(new string[] { result }, exportFileDeviation);
            }
            else
            {
                string exportFileDeviation = fileFolderName + ".NetworkParameter." + DateTime.Today.ToString("yyyy.mm.dd") + ".txt";
                IEnumerable<string> files = Directory.EnumerateFiles(Netutil.InPutDirector + (fileFolderName != "" ? "\\" + fileFolderName : ""));
                int i = 1;

               

                TextDB.WriteTextFile(new string[] {"File","Robustness", "Modularity", "HC entropy", "Density", "# of Drivers" }, exportFileDeviation);

                foreach (string fileName in files)
                {
                    BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileName);

                    Dictionary<Node, int> pCluster = null;

                    double mo = net.modularityWeightedDirected(ref pCluster);

                    Dictionary<string, double> HC = net.HierarchicalClosenessCentrality();

                    double HCent = BasicNetwork.EntropyOfNodes(HC);

                    string result = string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}/{6}", Netutil.ExtractFileNameFromPath(fileName), net.NetworkMutantRobustnessParalell(), mo, HCent, net.ArcDensity, net.driverNodes.Count(), net.Nodes.Count());
                    TextDB.WriteTextFile(new string[] { result }, exportFileDeviation);
                    

                    User.One.ShowWaitIndicator(i++, files.Count());
                }
            }

        }
        private static void OnCheckNetwork(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string fileName = Convert.ToString(Parameter[0].Value);
            BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileName);
            User.One.MessageToUser(string.Format("Network has {0,5} nodes and {1,5} links", net.Nodes.Count(), net.Arcs.Count()));
            foreach (var i in net.Arcs)
            {
                User.One.MessageToUser(string.Format("{0,5}--{1,10}-->{2,5}", i.startNode.ToString(),i.weight, i.endNode.ToString()));
            }
        }
        private static void OnNetworkRewireCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string fileName = Convert.ToString(Parameter[0].Value);
            int nNet = Convert.ToInt32(Parameter[1].Value);
            float fromRate = Convert.ToSingle(Parameter[2].Value);
            float toRate = Convert.ToSingle(Parameter[3].Value);
            bool calMo = Convert.ToBoolean(Parameter[4].Value);
            bool calRo = Convert.ToBoolean(Parameter[5].Value);
           
            string MoRoName = fileName.Substring(0, fileName.LastIndexOf('.')) + ".RoMo.txt";
            BooleanNetwork net = BooleanNetwork.ReadSignalingNetworkFile(fileName);
            User.One.MessageToUser("File \"" + fileName + "\" has been load successfully!\nBegin rewiring this file");


            TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}", "File", "Robustness", "Directed weighted Modularity"), MoRoName);
         
         
            double Ro = -1;
            double Mo = -1;
            for (int i = 0; i < nNet; i++)
            {
                User.One.ShowWaitIndicator(i , nNet);
                double al = Math.Round(fromRate + (toRate - fromRate) * Mathutil.NumericMath.RandomCraft.NextDouble(), 3);

                string rewiredFile = fileName.Substring(0, fileName.LastIndexOf('.')) + ".Rewire." + al.ToString() + ".txt";
                if (TextDB.Exists(rewiredFile))
                {
                    i--;
                    continue;
                }
                User.One.MessageToUser("Shuffling...");
                BooleanNetwork perturbNetwork = net.ShufflePreservingDegree((int)(al * net.Arcs.Count()), true) as BooleanNetwork;

                perturbNetwork.WriteToFile(rewiredFile);
                User.One.MessageToUser("Saved rewired file! "+rewiredFile);
                if (calMo)
                {
                    User.One.MessageToUser("Calculating modularity on file:"  + rewiredFile);
                    Dictionary<Node, int> pCluster = null;
                    Mo = perturbNetwork.modularityWeightedDirected(ref pCluster);
                }
                if (calRo)
                {
                    User.One.MessageToUser("Calculating robustness on file:" + rewiredFile);
                    Ro = perturbNetwork.NetworkMutantRobustnessParalell();
                }


                User.One.MessageToUser("Summarizing to file:" + MoRoName);
                TextDB.WriteTextFile(string.Format("{0}\t{1}\t{2}", rewiredFile, Ro, Mo), MoRoName);
                
                
            }
        }

        private static void OnNetworkRewireNetworkAnalysisCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string FileName = Convert.ToString(Parameter[0].Value);
            float fromRate = Convert.ToSingle(Parameter[1].Value);
            float toRate = Convert.ToSingle(Parameter[2].Value);
            int NetNum = Convert.ToInt32(Parameter[3].Value);

            BasicNet.Examination.SignalingStudy.AnalyzeModularityRobustnessWithRewiredNet(FileName, fromRate, toRate, NetNum);
        }

        private static void OnCalculateRobustnessPvalue(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int nNet = Convert.ToInt32(Parameter[0].Value),
                nSample = Convert.ToInt32(Parameter[1].Value),
                  nNodeFrom = Convert.ToInt32(Parameter[2].Value),
                  nNodeTo = Convert.ToInt32(Parameter[3].Value);
            string fileName = Convert.ToString(Parameter[4].Value);
            string IsSparseNets = Convert.ToString(Parameter[5].Value);

            BasicNet.Examination.SignalingStudy.CalculateRobustnessPvalue(nNet, nSample, nNodeFrom, nNodeTo, fileName, IsSparseNets.ToLower() == "y");
        }
        private static void OnAnalyzeModularityRobustnessRelationship(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int nNet = Convert.ToInt32(Parameter[0].Value),
                  nNodeFrom = Convert.ToInt32(Parameter[1].Value),
                  nNodeTo = Convert.ToInt32(Parameter[2].Value),
                  nMinLink = Convert.ToInt32(Parameter[3].Value),
                  nMaxLink = Convert.ToInt32(Parameter[4].Value);
            string ReportFileName = Convert.ToString(Parameter[5].Value);

            BasicNet.Examination.SignalingStudy.AnalyzeModularityRobustnessRelationship(nNet, nNodeFrom, nNodeTo, nMinLink, nMaxLink, ReportFileName);
            //BasicNet.Examination.SignalingStudy.AnalyzeModularityRobustnessRelationship_FixedModularity(nNet, nNodeFrom, nNodeTo, nMinLink, nMaxLink, ReportFileName);
        }
        private static void OnSelectRandomObjectByGroup(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string DataFile = Convert.ToString(Parameter[0].Value),
                 ResultFile = Convert.ToString(Parameter[1].Value);
                 
            int groupSize = Convert.ToInt32(Parameter[2].Value);

            BasicNet.Examination.SignalingStudy.SelectRandomObjectByGroup(DataFile, ResultFile, groupSize);
        }
        //
        private static void OnMoRoMutipleMutations(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int nNet = Convert.ToInt32(Parameter[0].Value),
                  nNodeFrom = Convert.ToInt32(Parameter[1].Value),
                  nNodeTo = Convert.ToInt32(Parameter[2].Value),
                  nMinLink = Convert.ToInt32(Parameter[3].Value),
                  nMaxLink = Convert.ToInt32(Parameter[4].Value);
            string ReportFileName = Convert.ToString(Parameter[5].Value);

            BasicNet.Examination.SignalingStudy.AnalyzeMoRoMutipleMutations(nNet, nNodeFrom, nNodeTo, nMinLink, nMaxLink, ReportFileName);
        }
        private static void OnAnalyzeMoRoHC(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int nNet = Convert.ToInt32(Parameter[0].Value),
                  nNodeFrom = Convert.ToInt32(Parameter[1].Value),
                  nNodeTo = Convert.ToInt32(Parameter[2].Value),
                  nMinLink = Convert.ToInt32(Parameter[3].Value),
                  nMaxLink = Convert.ToInt32(Parameter[4].Value);
            string ReportFileName = Convert.ToString(Parameter[5].Value);

            BasicNet.Examination.SignalingStudy.AnalyzeMoRoHC(nNet, nNodeFrom, nNodeTo, nMinLink, nMaxLink, ReportFileName);
        }
        //AnalyzeNetworkDegreeDistribution
        private static void OnAnalyzeNetworkDegreeDistribution(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string NetworkFile = Convert.ToString(Parameter[0].Value);

            BasicNet.Examination.SignalingStudy.AnalyzeNetworkDegreeDistribution(NetworkFile);
        }
        private static void OnAnalyzeMoRoByConfigureModel(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
             //new KeyValuePair<string,object>("# of networks",10), 
             //       new KeyValuePair<string,object>("The range of node From",20),
             //       new KeyValuePair<string,object>("The range of node To",40),  
             //       new KeyValuePair<string,object>("Powerlow of In-degree (0 = random)",0.0),
             //       new KeyValuePair<string,object>("Powerlow of Out-degree (0 = random)",0.0),
             //       new KeyValuePair<string,object>("Report file name","report.txt")

            int nNet = Convert.ToInt32(Parameter[0].Value),
                  nNodeFrom = Convert.ToInt32(Parameter[1].Value),
                  nNodeTo = Convert.ToInt32(Parameter[2].Value);
                double inDegPwr = Convert.ToDouble(Parameter[3].Value),
                  outDegPwr =  Convert.ToDouble(Parameter[4].Value);
            string ReportFileName = Convert.ToString(Parameter[5].Value);

            BasicNet.Examination.SignalingStudy.AnalyzeMoRoByConfigureModel(nNet, nNodeFrom, nNodeTo, inDegPwr, outDegPwr, ReportFileName);
        }
        private static void OnCompareModularityFunction(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int nNet = Convert.ToInt32(Parameter[0].Value),
                 nNodeFrom = Convert.ToInt32(Parameter[1].Value),
                 nNodeTo = Convert.ToInt32(Parameter[2].Value),
                 nMinLink = Convert.ToInt32(Parameter[3].Value),
                 nMaxLink = Convert.ToInt32(Parameter[4].Value);
            string ReportFileName = Convert.ToString(Parameter[5].Value);
            BasicNet.Examination.SignalingStudy.CompareModularityFunctions(nNet, nNodeFrom, nNodeTo, nMinLink, nMaxLink, ReportFileName);
        }


        private static void OnCalculateCompetitiveNetwork(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string networkFileName = Convert.ToString(Parameter[0].Value);
            string positiveString = Convert.ToString(Parameter[1].Value);
            string negativeString = Convert.ToString(Parameter[2].Value);
            string ReportFileName = Convert.ToString(Parameter[3].Value);

            BasicNet.Examination.SignalingStudy.CalculateCompetitiveNetwork(networkFileName, positiveString, negativeString, ReportFileName);
        }
        
        private static void OnCalculateCompetitiveRanking(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string networkFileName = Convert.ToString(Parameter[0].Value);
           
            string ReportFileName = Convert.ToString(Parameter[1].Value);

            BasicNet.Examination.SignalingStudy.CalculateCompetitiveRanking(networkFileName, ReportFileName);
        }
        
        private static void OnCalculateLoyalMatrixPoint(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string networkFileName = Convert.ToString(Parameter[0].Value);

            string ReportFileName = Convert.ToString(Parameter[1].Value);

            BasicNet.Examination.SignalingStudy.CalculateLoyalMatrixPoint(networkFileName, ReportFileName);
        }
        //CalculateLoyalPointWithLeader
        private static void OnCalculateLoyalPointWithLeader(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string networkFileName = Convert.ToString(Parameter[0].Value);
            string leaderName = Convert.ToString(Parameter[1].Value);
            string ReportFileName = Convert.ToString(Parameter[2].Value);

            BasicNet.Examination.SignalingStudy.CalculateLoyalPointWithLeader(networkFileName, leaderName, ReportFileName);
        }
        private static void OnCalculateTotalSupport(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string networkFileName = Convert.ToString(Parameter[0].Value);
            string ReportFileName = Convert.ToString(Parameter[1].Value);

            BasicNet.Examination.SignalingStudy.CalculateTotalSupport(networkFileName, ReportFileName);
        }
        
        private static void OnCalculateOptimumBranchings(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            string networkFileName = Convert.ToString(Parameter[0].Value);
            string ReportFileName = Convert.ToString(Parameter[1].Value);

            BasicNet.Examination.SignalingStudy.CalculateOptimumBranchings(networkFileName, ReportFileName);
        }
        private static void OnFastDensityCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            ComplexNetGenerator GeneratingNet = new BasicNet.ComplexNetGenerator();

            try
            {
                decimal Startdensity = Convert.ToDecimal(Parameter[0].Value);
                decimal Enddensity = Convert.ToDecimal(Parameter[1].Value);
                int fromNode = Convert.ToInt32(Parameter[2].Value), toNode = Convert.ToInt32(Parameter[3].Value);
                int NetNum = Convert.ToInt32(Parameter[4].Value);

                SignalingStudy.AnalyzeModularityRobustnessWithFixedDensity(Startdensity, Enddensity, fromNode, toNode, NetNum);
            }
            catch (ThreadAbortException)
            {

                User.One.MessageToUser("Aborted the network generating task");
            }
            catch (Exception ex)
            {

                User.One.SendErrorToUser(ex);
            }

        }
      
      
        private static void OnBenchmarkCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int num_nodes = Convert.ToInt32(Parameter[0].Value);
            double averagek = Convert.ToInt32(Parameter[1].Value);
            int maxk = Convert.ToInt32(Parameter[2].Value);
            double gamma = Convert.ToDouble(Parameter[3].Value);
            double beta = Convert.ToDouble(Parameter[4].Value);
            double mixing_parameter = Convert.ToDouble(Parameter[5].Value);


            int overlapping_nodes = Convert.ToInt32(Parameter[6].Value);
            int overlap_membership = Convert.ToInt32(Parameter[7].Value);
            int nmin =  Convert.ToInt32(Parameter[8].Value);
            int nmax = Convert.ToInt32(Parameter[9].Value);

            bool fixed_range = Convert.ToBoolean(Parameter[10].Value);
            bool excess = Convert.ToBoolean(Parameter[11].Value);
            bool defect = Convert.ToBoolean(Parameter[12].Value);

            string Network = Convert.ToString(Parameter[13].Value);
            Network = Netutil.ExtractMainFileName(Network) + DateTime.Now.ToString(".hmmss") + ".txt";
            string Community = Netutil.ExtractMainFileName(Network)+".Community.txt";
            string Analaysis = Netutil.ExtractMainFileName(Network) + ".Statistics.txt";
           

            Clustering cls = new Clustering();
            if (cls.benchmark(excess, defect, num_nodes, averagek, maxk, gamma, beta,
            mixing_parameter, overlapping_nodes, overlap_membership, nmin, nmax, fixed_range, Network, Community, Analaysis) == -1)
            {
                User.One.MessageToUser("Can not create benchmark network!");
                return;
            }
            User.One.MessageToUser("The benchmark network was saved in file "+Network);
        }
        static Dictionary<Node, int> ConvertToDisjointCommunity(Dictionary<int, List<int>> pCommunity, BasicNetwork template)
        {
            Dictionary<Node, int> disCom = new Dictionary<Node, int>();
            foreach (var e in pCommunity)
            {
                disCom.Add(template.NewNode(e.Key.ToString(), null), e.Value[0]);
            }
            return disCom;
        }
        private static void OnCompareBenchmarkCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
            int num_nets = Convert.ToInt32(Parameter[0].Value);
            int nodeFrom = Convert.ToInt32(Parameter[1].Value);
            int nodeTo = Convert.ToInt32(Parameter[2].Value);
            double gamma = Convert.ToDouble(Parameter[3].Value);
            bool isRandomGamma = (gamma <= 0 ? true : false);
            string ReportFileName = Convert.ToString(Parameter[4].Value);


            int averagek = 0;
            int maxk = 0;
            
            double beta = 0;

            double mixing_parameter = 0;// run

            int num_nodes = 0;
            int overlapping_nodes = 0;
            int overlap_membership = 0;
            int nmin = 0;
            int nmax = num_nodes;
            bool fixed_range = false;
            bool excess = false;
            bool defect = false;
            Dictionary<int, List<int>> pCommunity = null;
            BooleanNetwork Net = new BooleanNetwork();
            BasicNetwork NetTemp = null;
            int i = 0;

            TextDB.WriteTextFile(new string[] {"NetID", "Node #", "Link #", "Average degree","Gamma", "Beta","Mixing parmeter",
                    "Undirected unweighted Mo (1)", "Undirected weighted Mo (2)", "Directed weighted Mo (3)", "VarianceOfInformation1","VarianceOfInformation2","VarianceOfInformation3"
                     
                }, ReportFileName);
            Dictionary<Node, int> pCluster1 = null, pCluster2 = null, pCluster3 = null, pBenchmarkCluster=null;
            if (nodeFrom > nodeTo)
                throw new Exception("The range of node is invalid!");
            while (i++ < num_nets)
            {
                
                num_nodes = NumericMath.RandomCraft.Next(nodeFrom, nodeTo + 1);
                averagek = NumericMath.RandomCraft.Next(2, num_nodes-1);
                maxk = NumericMath.RandomCraft.Next(averagek, num_nodes);
                gamma = isRandomGamma ? 1.5 + NumericMath.RandomCraft.NextDouble() : gamma;
                beta = 0.5 + NumericMath.RandomCraft.NextDouble();
                mixing_parameter = NumericMath.RandomCraft.NextDouble();
                nmax = num_nodes;
                Clustering cls = new Clustering();
                try
                {
                    NetTemp = cls.benchmark(excess, defect, num_nodes, averagek, maxk, gamma, beta,
                    mixing_parameter, overlapping_nodes, overlap_membership, nmin, nmax, fixed_range, Net, ref pCommunity);
                }
                catch
                {
                    i--;
                    continue;
                }
                if (NetTemp == null)
                {
                    i--;
                    continue;
                }
                Net = NetTemp as BooleanNetwork;

                double undUnweightedMo1 = Net.modularity(ref pCluster1, false);
                double undWeightedMo2 = Net.modularity(ref pCluster2,true);
                double diMo3 = Net.modularityWeightedDirected(ref pCluster3);
                pBenchmarkCluster = ConvertToDisjointCommunity(pCommunity,Net);

                double vi1 = Clustering.DifferenceClusteringByVariationOfInformation(pCluster1, pBenchmarkCluster);
                double vi2 = Clustering.DifferenceClusteringByVariationOfInformation(pCluster2, pBenchmarkCluster);
                double vi3 = Clustering.DifferenceClusteringByVariationOfInformation(pCluster3, pBenchmarkCluster);

                int nNode = Net.Nodes.Count();
                int nLink = Net.Arcs.Count();



                string[] f = new string[] {Net.ObjectID.ToString(), nNode.ToString(), nLink.ToString(), averagek.ToString(),gamma.ToString(),beta.ToString(),mixing_parameter.ToString(),
                            undUnweightedMo1.ToString(), undWeightedMo2.ToString(),diMo3.ToString(),vi1.ToString(),vi2.ToString(),vi3.ToString()
                        };

                TextDB.WriteTextFile(f, ReportFileName);

                User.One.ShowWaitIndicator(i, num_nets);
            }
            User.One.MessageToUser("The result is saved at" + ReportFileName);
 
        }
        //private static void OnMoRoBenchmarkCommand(Dictionary<int, KeyValuePair<string, object>> Parameter)
        //{
        //    int num_nets = Convert.ToInt32(Parameter[0].Value);
        //    int nodeFrom = Convert.ToInt32(Parameter[1].Value);
        //    int nodeTo = Convert.ToInt32(Parameter[2].Value);
        //    int maxAveragek = Convert.ToInt32(Parameter[3].Value);
        //    double gamma = Convert.ToDouble(Parameter[4].Value);
        //    bool isRandomGamma = (gamma <= 0 ? true : false);
        //    int Motype = Convert.ToInt32(Parameter[5].Value);
        //    string ReportFileName = Convert.ToString(Parameter[6].Value);
        //     //"Modularity type (1 = directed weighted, 2 = undirected weighted, otherwise = undirected unweighted)"
        //    string MoName=Motype==1?"Directed":(Motype==2?"Undirected weighted":"Undirected unweighted");

        //    //int averagek = 0;
        //    int maxk = 0;
           
        //    double beta = 0;

        //    double mixing_parameter = 0;// run
        //    int averagek = 0;
        //    int num_nodes = 0;
        //    int overlapping_nodes = 0;
        //    int overlap_membership = 0;
        //    int nmin = 0;
        //    int nmax = num_nodes;
        //    bool fixed_range = false;
        //    bool excess = false;
        //    bool defect = false;
        //    Dictionary<int, List<int>> pCommunity = null;
        //    BooleanNetwork Net = new BooleanNetwork();
        //    BasicNetwork NetTemp = null;
            

        //    TextDB.WriteTextFile(new string[] {"NetID", "Node #", "Edge #","Link #", "Average degree","Gamma", "Beta","Mixing parmeter",
        //            MoName+" modularity", "Robustness", "In-module robustness", "Out-module robustness"
                     
        //        }, ReportFileName);
        //    Dictionary<Node, int> pCluster = null;
        //    if (nodeFrom > nodeTo)
        //        throw new Exception("The range of node is invalid!");
        //    //while (i++ < num_nets)
        //    for(int i=0;i<num_nets;i++)
        //    {
        //        User.One.ShowWaitIndicator(i, num_nets);

        //        num_nodes = NumericMath.RandomCraft.Next(nodeFrom, nodeTo + 1);
        //        averagek = NumericMath.RandomCraft.Next(1, Math.Min(num_nodes - 1, maxAveragek));//in order to have sparse network
        //        maxk = NumericMath.RandomCraft.Next(averagek, num_nodes);
        //        gamma = isRandomGamma?NumericMath.RandomCraft.Next(0,3) + NumericMath.RandomCraft.NextDouble():gamma;
        //        beta = NumericMath.RandomCraft.Next(0,3)+ NumericMath.RandomCraft.NextDouble();
        //        mixing_parameter = NumericMath.RandomCraft.NextDouble();
        //        nmax = num_nodes;
        //        Clustering cls = new Clustering();
        //        try
        //        {
        //            NetTemp = cls.benchmark(excess, defect, num_nodes, averagek, maxk, gamma, beta,
        //            mixing_parameter, overlapping_nodes, overlap_membership, nmin, nmax, fixed_range, Net, ref pCommunity);
        //        }
        //        catch
        //        {
        //            i--;
        //            continue;
        //        }
        //        if (NetTemp == null)
        //        {
        //            i--;
        //            continue;
        //        }
        //        Net = NetTemp as BooleanNetwork;

               
        //        double Mo = (Motype==1?Net.modularityWeightedDirected(ref pCluster):(Motype==2?Net.modularity(ref pCluster,true):Net.modularity(ref pCluster,false)));
        //        double Ro = Net.NetworkMutantRobustnessParalell();
        //        double outRo = 0,inRo=0;
        //        Net.InOutModuleRobustnessParalell(pCluster, new Perturbation(), ref inRo, ref outRo);

        //        int nNode = Net.Nodes.Count();
        //        int nEdge = Net.EdgesWithoutSelfLoops.Count();
        //        int nLink = Net.Arcs.Count();

        //        //"NetID", "Node #", "Selfloop node#", "Edge #","Link #","Selfloop link#", "Average degree","Gamma", "Beta","Mixing parmeter",
        //        string[] f = new string[] {Net.ObjectID.ToString(), nNode.ToString(), nEdge.ToString(),nLink.ToString(),
        //            averagek.ToString(),gamma.ToString(),beta.ToString(),mixing_parameter.ToString(),
        //                    Mo.ToString(), Ro.ToString(),inRo.ToString(),outRo.ToString()
        //                };

        //        TextDB.WriteTextFile(f, ReportFileName);

                
        //    }
        //    User.One.MessageToUser("The result is saved at" + ReportFileName);
        //}

        private static void OnMoRoBenchmarkCommand2(Dictionary<int, KeyValuePair<string, object>> Parameter)
        {
             //new KeyValuePair<string,object>("# of benchmark networks",1000), 
             //       new KeyValuePair<string,object>("# of node in each network From",50),
             //       new KeyValuePair<string,object>("# of node in each network To",200),
             //       new KeyValuePair<string,object>("Average of in-degree (0 = random)",2.1538),//HSN2013=6.9195
             //       new KeyValuePair<string,object>("Maximum in-degree (0 = random)",31),//HSN2013=248
             //       new KeyValuePair<string,object>("Minus exponent for degree distribution (0 = random) ",1.998),//HSN2013=1.529
             //       new KeyValuePair<string,object>("Modularity type (1 = directed weighted, 2 = undirected weighted, otherwise = undirected unweighted)",1),
             //       new KeyValuePair<string,object>("Output report file name","moro.bench.txt")

            int num_nets = Convert.ToInt32(Parameter[0].Value);
            int nodeFrom = Convert.ToInt32(Parameter[1].Value);
            int nodeTo = Convert.ToInt32(Parameter[2].Value);

            double averagek = Convert.ToDouble(Parameter[3].Value);
            bool IsRandomAverageK = (averagek<=0?true:false);

            int maxk = Convert.ToInt32(Parameter[4].Value);
            bool IsRandomMaxK = (maxk <= 0 ? true : false);

            double gamma = Convert.ToDouble(Parameter[5].Value);
            bool isRandomGamma = (gamma <= 0 ? true : false);

            int Motype = Convert.ToInt32(Parameter[6].Value);
            string ReportFileName = Convert.ToString(Parameter[7].Value);
            //"Modularity type (1 = directed weighted, 2 = undirected weighted, otherwise = undirected unweighted)"
            string MoName = Motype == 1 ? "Directed" : (Motype == 2 ? "Undirected weighted" : "Undirected unweighted");

            //int averagek = 0;
            //int maxk = 0;

            double beta = 0;

            double mixing_parameter = 0;// run
            //int averagek = 0;
            int num_nodes = 0;
            int overlapping_nodes = 0;
            int overlap_membership = 0;
            int nmin = 0;
            int nmax = num_nodes;
            bool fixed_range = false;
            bool excess = false;
            bool defect = false;
            Dictionary<int, List<int>> pCommunity = null;
            BooleanNetwork Net = new BooleanNetwork();
            BasicNetwork NetTemp = null;

            User.One.MessageToUser("We turn off messages, for there are a lot of messages (from core of the software published by Physical Review E80, 016118 (2009)) while generating random benchmark graphs!");
            User.One.LockWritingMessage();
            TextDB.WriteTextFile(new string[] {"NetID","IsConnected", "Node #", "Edge #","Link #", "Average degree","Gamma", "Beta","Mixing parmeter",
                    MoName+" modularity", "Robustness", "In-module robustness", "Out-module robustness",
                     "In-power law", "In-R", "In-Pvalue", "Out-power law","Out-R","Out-Pvalue"
                     
                }, ReportFileName);
            Dictionary<Node, int> pCluster = null;
            if (nodeFrom > nodeTo)
                throw new Exception("The range of node is invalid!");
            //while (i++ < num_nets)

            for (int i = 0; i < num_nets; i++)
            {
                User.One.ShowWaitIndicator(i, num_nets);

                num_nodes = NumericMath.RandomCraft.Next(nodeFrom, nodeTo + 1);
                averagek = IsRandomAverageK ? NumericMath.RandomCraft.Next(1, num_nodes - 1) : averagek;
                maxk = IsRandomMaxK ? NumericMath.RandomCraft.Next((int)averagek, num_nodes) : maxk;
                gamma = isRandomGamma ? NumericMath.RandomCraft.Next(0, 3) + NumericMath.RandomCraft.NextDouble() : gamma;
                beta = NumericMath.RandomCraft.Next(0, 3) + NumericMath.RandomCraft.NextDouble();
                mixing_parameter = NumericMath.RandomCraft.NextDouble();
                nmax = num_nodes;
                Clustering cls = new Clustering();
                try
                {
                    NetTemp = cls.benchmark(excess, defect, num_nodes, averagek, maxk, gamma, beta,
                    mixing_parameter, overlapping_nodes, overlap_membership, nmin, nmax, fixed_range, Net, ref pCommunity);
                }
                catch
                {
                    i--;
                    continue;
                }
                if (NetTemp == null)
                {
                    i--;
                    continue;
                }
                Net = NetTemp as BooleanNetwork;


                double Mo = (Motype == 1 ? Net.modularityWeightedDirected(ref pCluster) : (Motype == 2 ? Net.modularity(ref pCluster, true) : Net.modularity(ref pCluster, false)));
                double Ro = Net.NetworkMutantRobustnessParalell();
                double outRo = 0, inRo = 0;
                Net.InOutModuleRobustnessParalell(pCluster, new Perturbation(), ref inRo, ref outRo);

                int nNode = Net.Nodes.Count();
                int nEdge = Net.EdgesWithoutSelfLoops.Count();
                int nLink = Net.Arcs.Count();
                int IsConnected = Net.IsConnected ? 1 : 0;

                double inGamma = 0, outGamma = 0, inR = 0, outR = 0;
                double inPvalue = 0, outPvalue = 0;
                Netutil.FitDegreeDistribution(Net, ref inGamma, ref inR, ref inPvalue, ref outGamma, ref outR, ref outPvalue);

                //"NetID", "Node #", "Selfloop node#", "Edge #","Link #","Selfloop link#", "Average degree","Gamma", "Beta","Mixing parmeter",
                string[] f = new string[] {Net.ObjectID.ToString(),IsConnected.ToString(), nNode.ToString(), nEdge.ToString(),nLink.ToString(),
                    averagek.ToString(),gamma.ToString(),beta.ToString(),mixing_parameter.ToString(),
                            Mo.ToString(), Ro.ToString(),inRo.ToString(),outRo.ToString(),
                            inGamma.ToString(),inR.ToString(),inPvalue.ToString(),outGamma.ToString(),outR.ToString(),outPvalue.ToString()
                        };
                // "In-power law", "In-R", "In-Pvalue", "Out-power law","Out-R","Out-Pvalue"
                TextDB.WriteTextFile(f, ReportFileName);


            }
            User.One.MessageToUser("The result is saved at" + ReportFileName);
        }
        
#endregion

        #endregion
    }
}
